apiVersion: apps/v1
kind: Deployment
metadata:
  name:  offer-app
  namespace: newapp
  labels:
    app:  offer-app
spec:
  selector:
    matchLabels:
      app: offer-app
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  offer-app
    spec:
      containers:
      - name:  offer-app
        image:  subodhgholap/offers-app:latest
        ports:
        - containerPort:  1001
          name:  offer-app
          
---

apiVersion: v1
kind: Service
metadata:
  name: offer
  namespace: newapp
spec:
  selector:
    app: "offer-app"
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: offer
    port: 1001
    targetPort: 1001
