apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "cart-app"
  namespace: newapp
  labels:
    app:  "cart-app"
spec:
  selector:
    matchLabels:
      app: "cart-app"
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  "cart-app"
    spec:
      containers:
      - name:  "cart-app"
        image:  subodhgholap/cart-app:latest
        ports:
        - containerPort:  1004
          name:  "cart-app"

---

apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: newapp
spec:
  selector:
    app: "cart-app"
  type: ClusterIP
  ports:
  - name: cart
    port: 1004
    targetPort: 1004
    